// Canonical creature archive records, preserved from the original bestiary.
window.TBH_BESTIARY_RECORDS = [
  {
    id: "puru-beast",
    group: "wildlife",
    status: "confirmed",
    accent: "#70e5dc",
    zhName: "噗噜兽",
    enName: "Puru Beast",
    zhSubtitle: "温顺的磁结节群居兽",
    enSubtitle: "Gentle magnetic-nodule herd animal",
    zhSummary: "一种与星际物流文明形成稳定共生关系的温顺外星群居兽。它们不是被制造出来的运输工具，而是凭借强健身体、社会性与背部磁结节，自然进入了港口和航线生态。",
    enSummary: "A gentle alien herd species that has formed a stable partnership with interstellar logistics. Puru Beasts were never engineered as cargo tools; their strength, social nature, and dorsal magnetic nodules made them natural companions of ports and trade routes.",
    zhClass: "自然生命 · 奇兽",
    enClass: "Natural life · Wildlife",
    zhHabitat: "轨道港、温带殖民地、货运栖息舱",
    enHabitat: "Orbital ports, temperate colonies, freight habitats",
    zhDiet: "高纤维外星植料与矿物盐",
    enDiet: "Fibrous alien forage and mineral salts",
    zhActivity: "昼行 · 群居 · 可驯养",
    enActivity: "Diurnal · Social · Trainable",
    zhEcology: "野生噗噜兽会以家庭群为单位迁徙，成年个体围成松散外圈，让幼兽在内部休息。背部磁结节能感知局部磁场并吸附轻量矿物，在人类港口中则可连接不会刺穿皮肤的模块化货架。",
    enEcology: "Wild Puru travel in family herds. Adults form a loose outer ring while calves rest within. Their dorsal nodules sense local magnetic fields and collect light minerals; in human ports they accept modular racks that attach without piercing the skin.",
    zhRelations: "自由航商会把成年噗噜视为可靠的货运伙伴，并为跨航线个体登记休息周期与家庭关系。幼兽好奇、奔跑速度惊人，常成为货运站事故报告里最无害却最频繁的主角。",
    enRelations: "The Free Trade Guild treats mature Puru as logistics partners and records rest cycles and family bonds across routes. Juveniles are curious and unexpectedly fast, making them frequent—but usually harmless—subjects of port incident reports.",
    zhTraits: ["海泡绿短毛与暖奶油色面罩", "珊瑚色内侧的柔性高耸感知耳鳍", "四至六枚珍珠质背部磁结节", "带青色星形高光的深色眼睛", "情绪增强时变亮的青色面颊星斑", "成年个体通过普通生长变得更长、更宽、更沉稳"],
    enTraits: ["Seafoam coat with a warm cream facial mask", "Tall flexible sensory ear-fins with coral inner surfaces", "Four to six pearlescent dorsal magnetic nodules", "Dark eyes with cyan star-shaped catchlights", "Cyan cheek freckles that brighten with emotion", "Adults grow longer, broader, heavier, and calmer without metamorphosis"],
    tagsZh: ["群居", "港口共生", "磁场感知", "货运伙伴", "温顺"],
    tagsEn: ["Herd", "Port symbiosis", "Magnetic sense", "Cargo partner", "Gentle"],
    illustration: "./assets/creature-concepts/puru-beast/illustration.png",
    concept: "./assets/creature-concepts/puru-beast/concept-sheet.png",
    specimens: [
      { src: "./assets/card-art/rampaging-puru-beast/rampaging-puru-beast-01.png", zh: "横行噗噜兽 · 青年个体", en: "Rampaging Puru · Young adult" },
      { src: "./assets/card-art/cargo-puru-beast/cargo-puru-beast-01.png", zh: "货运噗噜兽 · 成年工作个体", en: "Cargo Puru · Mature worker" }
    ]
  },
  {
    id: "borrowed-time-mayfly",
    group: "wildlife",
    status: "confirmed",
    accent: "#9edcff",
    zhName: "借时蜉蝣",
    enName: "Borrowed-Time Mayfly",
    zhSubtitle: "在数分钟里度过数十年的静域昆虫",
    enSubtitle: "A stasis insect that lives decades within minutes",
    zhSummary: "栖息于废弃静域设施附近的米级昆虫。成虫在外界只存活数分钟，却会在自己的主观时间中经历漫长成年期；整个族群能在一次站内晨曦里完成羽化、求偶与死亡。",
    enSummary: "Meter-scale insects found around abandoned stasis facilities. Adults survive only minutes to outside observers while experiencing decades of subjective adulthood; a colony can emerge, mate, and die within one station dawn.",
    zhClass: "自然生命 · 时域适应种",
    enClass: "Natural life · Temporal-adapted",
    zhHabitat: "废弃静域发生器、冷却池与时间残响区",
    enHabitat: "Abandoned stasis generators, cooling pools, temporal echoes",
    zhDiet: "幼体滤食冷却池微生物；成虫几乎不摄食",
    enDiet: "Larvae filter cooling-pool microbes; adults barely feed",
    zhActivity: "集体羽化 · 极短外部寿命",
    enActivity: "Mass emergence · Extremely brief external life",
    zhEcology: "幼体长期潜伏在静域冷却液形成的浅池中，只在残余界膜达到特定振幅时同时羽化。翅膜上的同心环不是机械刻度，而是组织在不同时间速率下留下的生长纹。",
    enEcology: "Larvae remain in shallow pools formed by stasis coolant and emerge together only when remnant field membranes reach a specific amplitude. Concentric wing rings are not machinery but growth marks laid down at different temporal rates.",
    zhRelations: "零秒学派利用蜉蝣羽化时间判断废墟是否仍有活动时痕；黑市则会捕捉成虫制作非法静域校准器。离开原生场域后，它们通常会迅速失去时间稳定性。",
    enRelations: "Zero-Second researchers use emergence timing to detect active time scars. Black markets trap adults for illegal stasis calibration, though the insects rapidly lose temporal stability outside their native field.",
    zhTraits: ["珍珠质分节外骨骼", "四片带同心生长环的透明翅膜", "同一个体不同年龄阶段的相位残影", "细长尾丝和可感知界膜振动的触角"],
    enTraits: ["Pearlescent segmented exoskeleton", "Four transparent wings with concentric growth rings", "Phase echoes of the same animal at different ages", "Long tail filaments and membrane-sensitive antennae"],
    tagsZh: ["静域", "集体羽化", "主观长寿", "短命", "环境指示种"],
    tagsEn: ["Stasis", "Mass emergence", "Subjective longevity", "Short-lived", "Indicator species"],
    illustration: "./assets/creature-concepts/borrowed-time-mayfly/illustration.png",
    concept: "./assets/creature-concepts/borrowed-time-mayfly/concept-sheet.png"
  },
  {
    id: "navigation-sailbeast",
    group: "wildlife",
    status: "confirmed",
    accent: "#78cfff",
    zhName: "航灯帆兽",
    enName: "Navigation Sailbeast",
    zhSubtitle: "沿恒星风迁徙的活体航标",
    enSubtitle: "A living beacon that migrates on stellar wind",
    zhSummary: "巨型真空适应生物，能够展开三叶式生物光帆并顺恒星风跨越航区。腹部发光器官会持续校正安全方向，令迁徙群成为天然的深空航标。",
    enSummary: "A gigantic vacuum-adapted organism whose three-lobed living sails carry it across regions on stellar wind. Ventral photophores continually align toward safer corridors, turning migrations into natural deep-space beacons.",
    zhClass: "自然生命 · 真空迁徙种",
    enClass: "Natural life · Vacuum migrant",
    zhHabitat: "恒星风通道、轨道巨构外缘、低尘航区",
    enHabitat: "Stellar-wind corridors, megastructure rims, low-dust routes",
    zhDiet: "带电尘埃、恒星风粒子与稀薄气体",
    enDiet: "Charged dust, stellar particles, and trace gas",
    zhActivity: "长距离迁徙 · 小群活动",
    enActivity: "Long migration · Small groups",
    zhEcology: "帆兽通过宽阔而薄的三叶帆膜收集带电粒子，同时借光压和磁场改变轨迹。幼体跟随成年个体腹部的青琥珀色灯列学习迁徙路线。它们不会在真空中像鱼一样摆动游泳。",
    enEcology: "Sailbeasts gather charged particles with broad three-lobed membranes, steering through radiation pressure and magnetic fields. Juveniles learn migration paths by following cyan-amber ventral light rows. They do not swim through vacuum like fish.",
    zhRelations: "航商测绘船通常保持距离伴飞，以迁徙群判断航道季节性变化；擅自改变灯列或驱赶兽群被视为会危及整条航线的重罪。",
    enRelations: "Guild survey craft accompany herds at a respectful distance to read seasonal route changes. Spoofing their light rows or driving away a migration is treated as a crime against the entire corridor.",
    zhTraits: ["梭形脊骨与明显腹部龙骨", "三叶式半透明生物帆", "青色与琥珀色腹部光点", "柔性矿物质皮肤和低阻力头部"],
    enTraits: ["Spindle body with a pronounced ventral keel", "Three-lobed translucent living sails", "Cyan and amber ventral photophores", "Flexible mineral skin and a low-drag head"],
    tagsZh: ["恒星风", "迁徙", "活体航标", "真空生态", "航商保护"],
    tagsEn: ["Stellar wind", "Migration", "Living beacon", "Vacuum ecology", "Guild protection"],
    illustration: "./assets/creature-concepts/navigation-sailbeast/illustration.png",
    concept: "./assets/creature-concepts/navigation-sailbeast/concept-sheet.png"
  },
  {
    id: "star-shell-packbeast",
    group: "wildlife",
    status: "confirmed",
    accent: "#8ee8e8",
    zhName: "星壳驮兽",
    enName: "Star-Shell Packbeast",
    zhSubtitle: "背负矿脉与微型生态的六足重兽",
    enSubtitle: "A six-legged giant carrying ore and micro-ecology",
    zhSummary: "生活在小行星矿区的六足重型食矿兽。其层叠背甲会静电吸附宇宙尘埃，并在长期休息时缓慢结晶出低纯度星能矿。",
    enSummary: "A massive six-legged mineral grazer of asteroid belts. Its layered dorsal shell electrostatically gathers cosmic dust and slowly crystallizes low-grade star-energy deposits while the animal rests.",
    zhClass: "自然生命 · 食矿巨兽",
    enClass: "Natural life · Mineral grazer",
    zhHabitat: "小行星矿带、低重力荒原、露天采矿营地",
    enHabitat: "Asteroid belts, low-gravity barrens, open mining camps",
    zhDiet: "硅酸盐、含铁岩屑与微量星能矿",
    enDiet: "Silicates, ferrous rubble, and trace star ore",
    zhActivity: "缓慢群居 · 长时间静止",
    enActivity: "Slow herds · Long stationary periods",
    zhEcology: "六条承重腿把重量分散到松散地表，楔形头部从岩层中刮取矿物。老年个体的背甲沟槽会积聚水分、苔状生物和结晶体，逐渐形成可随迁徙移动的小型生态岛。",
    enEcology: "Six load-bearing legs spread weight across loose terrain while a wedge-shaped head scrapes minerals from rock. Grooves on old animals collect moisture, moss-like growth, and crystals, becoming moving ecological islands.",
    zhRelations: "负责任的矿工只收集背甲最外层的成熟晶簇，并在兽群移动前拆除脚手架。过度采掘会损坏保温甲层，曾引发多起殖民地禁采令。",
    enRelations: "Responsible miners harvest only mature outer crystals and remove scaffolds before a herd moves. Deep extraction damages insulating shell layers and has prompted several colonial mining bans.",
    zhTraits: ["低伏的长躯干与三对承重腿", "楔形掘食头部", "可吸附尘埃的层状矿物背甲", "老年背甲上的晶簇与共生植被"],
    enTraits: ["Low elongated body with three pairs of load-bearing legs", "Wedge-shaped grazing head", "Layered mineral shell that collects dust", "Crystals and symbiotic growth on old shells"],
    tagsZh: ["食矿", "星能结晶", "采矿共生", "六足", "移动生态岛"],
    tagsEn: ["Mineral grazer", "Star crystallization", "Mining symbiosis", "Six-legged", "Moving ecosystem"],
    illustration: "./assets/creature-concepts/star-shell-packbeast/illustration.png",
    concept: "./assets/creature-concepts/star-shell-packbeast/concept-sheet.png"
  },
  {
    id: "sun-amber-swarm",
    group: "wildlife",
    status: "confirmed",
    accent: "#ffab45",
    zhName: "日珀蜂群",
    enName: "Sun-Amber Swarm",
    zhSubtitle: "把日冕热量筑成琥珀蜂巢的群落昆虫",
    enSubtitle: "Colonial insects that build hives from coronal heat",
    zhSummary: "栖息在戴森环散热结构上的辐射摄食昆虫。工蜂把过量热能固化进橙金色日珀蜂房，使蜂巢同时成为群落育幼区与天然热沉。",
    enSummary: "Radiation-feeding insects that inhabit Dyson heat structures. Workers lock excess heat into amber combs, making each hive both a nursery and a living thermal sink.",
    zhClass: "自然生命 · 群落昆虫",
    enClass: "Natural life · Colonial insect",
    zhHabitat: "戴森环外缘、日冕采集塔、散热井",
    enHabitat: "Dyson rims, coronal collectors, thermal shafts",
    zhDiet: "高能粒子、热辐射与金属表面微生物",
    enDiet: "Energetic particles, thermal radiation, surface microbes",
    zhActivity: "恒温群落 · 工蜂轮班",
    enActivity: "Thermoregulated colony · Worker shifts",
    zhEcology: "工蜂以半透明陶瓷翅膜散热，并将吸收的能量传入蜂房。蜂后很少暴露在直射日光下，始终被低温琥珀层和护理蜂包围。它们只有在热沉结构遭到破坏时才会集体防卫。",
    enEcology: "Workers shed heat through translucent ceramic wings and transfer gathered energy into the comb. The queen remains under cooler amber layers and nurse workers, and the colony mounts a mass defense only when its thermal structure is damaged.",
    zhRelations: "烈阳教会把大型蜂巢视为太阳允许生命靠近的证据；环带工程师则会在不破坏育幼区的前提下，引导蜂群为旧散热塔降温。",
    enRelations: "The Solar Church regards great hives as proof that the sun permits life to draw near. Ring engineers guide colonies into old heat towers without disturbing brood chambers.",
    zhTraits: ["黑色与象牙色节甲", "沿甲片流动的橙色日冕纹", "半透明陶瓷翅膜", "储存热量的蜂窝状日珀结构"],
    enTraits: ["Black and ivory segmented armor", "Orange coronal lines between plates", "Translucent ceramic wings", "Honeycomb sun-amber structures that store heat"],
    tagsZh: ["戴森环", "群落", "热沉", "日冕摄食", "烈阳圣兽"],
    tagsEn: ["Dyson ring", "Colony", "Heat sink", "Coronal feeding", "Solar sacred fauna"],
    illustration: "./assets/creature-concepts/sun-amber-swarm/illustration.png",
    concept: "./assets/creature-concepts/sun-amber-swarm/concept-sheet.png"
  },
  {
    id: "rust-eater-clawbeast",
    group: "wildlife",
    status: "confirmed",
    accent: "#e58f62",
    zhName: "食锈螯兽",
    enName: "Rust-Eater Clawbeast",
    zhSubtitle: "吞食工业废料并留下陶瓷补丁的废墟清道夫",
    enSubtitle: "A ruin scavenger that leaves ceramic repairs behind",
    zhSummary: "黑午裂变后扩散于工业遗迹的八肢甲壳兽。它们以锈蚀金属和失效纳米材料为食，并排出高强度浅色陶瓷浆，常在觅食过程中意外封住舰体裂缝。",
    enSummary: "Eight-limbed arthropods that spread through industrial ruins after the Black Noon. They consume rusted metal and dead nanomaterial, then extrude strong pale ceramic slurry that often seals hull breaches by accident.",
    zhClass: "自然生命 · 工业腐食种",
    enClass: "Natural life · Industrial scavenger",
    zhHabitat: "坠毁舰体、废弃工厂、裂变城市下层",
    enHabitat: "Wrecked ships, abandoned factories, lower ruin cities",
    zhDiet: "氧化金属、失效纳米机群与复合材料",
    enDiet: "Oxidized metal, dead nanomachines, composites",
    zhActivity: "夜行群落 · 沿锈蚀带觅食",
    enActivity: "Nocturnal colony · Follows corrosion fronts",
    zhEcology: "前方巨螯先压碎金属，口器再筛选可消化的氧化物。无法吸收的陶瓷成分会在腹部腺体中重排，成为黏附力极强的修补浆。幼体通常生活在成年个体留下的陶瓷孔洞中。",
    enEcology: "Massive foreclaws crush metal before mouthparts sort digestible oxides. Ceramic residue is reorganized in abdominal glands into highly adhesive repair slurry. Juveniles shelter in ceramic cavities left by adults.",
    zhRelations: "Astra 回收队会利用声振诱导群落清理大型残骸，但禁止把它们带入仍运行的船坞——食锈螯兽无法区分报废金属和暂时停机的设备。",
    enRelations: "Astra salvage teams use vibration lures to guide colonies through large wrecks, but ban them from active docks: clawbeasts cannot distinguish scrap from machinery that is merely powered down.",
    zhTraits: ["八条关节肢与两枚前置陶瓷巨螯", "锈红甲壳和浅色陶瓷背板", "成列青色感知坑", "腹部陶瓷浆分泌器官"],
    enTraits: ["Eight jointed limbs and two forward ceramic crushing claws", "Rust-red shell with pale ceramic plates", "Rows of cyan sensory pits", "Abdominal ceramic-slurry organ"],
    tagsZh: ["工业废墟", "腐食", "陶瓷修复", "群落", "回收利用"],
    tagsEn: ["Industrial ruins", "Scavenger", "Ceramic repair", "Colony", "Salvage"],
    illustration: "./assets/creature-concepts/rust-eater-clawbeast/illustration.png",
    concept: "./assets/creature-concepts/rust-eater-clawbeast/concept-sheet.png"
  },
  {
    id: "echo-homing-beast",
    group: "wildlife",
    status: "confirmed",
    accent: "#78dcff",
    zhName: "回声归巢兽",
    enName: "Echo Homing Beast",
    zhSubtitle: "以胸腔共鸣追寻出生行星的盲眼迁徙兽",
    enSubtitle: "An eyeless migrant that follows its birthworld's resonance",
    zhSummary: "没有视觉器官的群居四足兽，通过多层胸腔共鸣膜感知行星引力的微弱回声。它们一生都能指出出生地的方向，即使那颗星球已经毁灭。",
    enSummary: "Eyeless social quadrupeds that sense faint planetary gravity echoes through layered chest membranes. They point toward their birthworld throughout life, even after that world has been destroyed.",
    zhClass: "自然生命 · 引力感知种",
    enClass: "Natural life · Gravitational sensor",
    zhHabitat: "迁徙舰、月面谷地、低干扰观测站",
    enHabitat: "Migration ships, lunar valleys, quiet observatories",
    zhDiet: "高蛋白苔类、盐藓与培养饲料",
    enDiet: "Protein moss, salt lichen, cultivated forage",
    zhActivity: "晨昏鸣唱 · 集体定向",
    enActivity: "Twilight calling · Collective orientation",
    zhEcology: "群体会在固定时刻排列朝向同一方向，通过喉部与肋骨间的青色膜片发出低频鸣声。幼兽先模仿成年个体，随后逐渐锁定属于自己的出生地回声。",
    enEcology: "At fixed times the herd aligns in one direction and sounds low calls through cyan membranes between throat and ribs. Calves imitate adults before gradually locking onto the echo of their own birthplace.",
    zhRelations: "早期殖民舰曾把它们当作失灵时仍可靠的活体罗盘；如今幸存者也会饲养来自失落家园的兽群，让每日归巢鸣唱成为纪念仪式。",
    enRelations: "Early colony ships kept them as living compasses that survived instrument failure. Survivors now maintain herds from lost worlds, turning each daily homing call into an act of remembrance.",
    zhTraits: ["无眼的暖象牙色面甲", "午夜蓝皮毛与定向耳冠", "胸腹两组青色共鸣腔", "适合长途迁徙的细长四肢"],
    enTraits: ["Eyeless warm-ivory facial shield", "Midnight coat and directional ear crown", "Cyan resonant chambers in throat and ribs", "Long limbs suited to migration"],
    tagsZh: ["引力回声", "归巢", "群居", "活体罗盘", "纪念仪式"],
    tagsEn: ["Gravity echo", "Homing", "Herd", "Living compass", "Memorial"],
    illustration: "./assets/creature-concepts/echo-homing-beast/illustration.png",
    concept: "./assets/creature-concepts/echo-homing-beast/concept-sheet.png"
  },
  {
    id: "riftsurf-diver",
    group: "wildlife",
    status: "confirmed",
    accent: "#5fbfff",
    zhName: "裂潮潜兽",
    enName: "Riftsurf Diver",
    zhSubtitle: "沿时间裂隙边缘进行受控相位潜跃的六肢兽",
    enSubtitle: "A six-limbed animal that phase-dives along time rifts",
    zhSummary: "能够短暂离开当前时刻、沿裂隙边缘滑行的六肢生物。它们的身体结构始终连贯，相位过程也高度可控，因此与解剖矛盾的空亡体有本质区别。",
    enSummary: "A six-limbed animal that briefly leaves the present moment to glide along a rift edge. Its anatomy remains coherent and its phase sequence controlled, making it fundamentally different from contradictory Hollow-Nulls.",
    zhClass: "自然生命 · 裂隙边缘种",
    enClass: "Natural life · Rift-edge species",
    zhHabitat: "低强度裂隙、封锁线外缘、时潮暗流",
    enHabitat: "Low-intensity rifts, blockade edges, temporal currents",
    zhDiet: "裂隙浮游生物与相位化有机碎屑",
    enDiet: "Rift plankton and phase-shifted organic debris",
    zhActivity: "伏击与潜跃 · 独居或母幼同行",
    enActivity: "Ambush and phase-diving · Solitary or mother-young pairs",
    zhEcology: "压力翼能读取裂隙边缘的时序梯度，叉状感知冠负责选择重新进入现实时的落点。潜跃不是随机消失，而是依次经过数个可预测的缺席阶段。",
    enEcology: "Pressure vanes read temporal gradients while the forked sensory crown selects a safe point of return. A dive is not random disappearance but a sequence of predictable absent phases.",
    zhRelations: "猎空同盟的走私船会跟随成年个体穿越封锁区，幼兽也偶尔在温暖货舱里筑巢。试图用诱饵强迫潜兽改道往往会让整条裂隙路径失去稳定参照。",
    enRelations: "Raider smugglers follow adults through blockades, and juveniles sometimes nest in warm cargo holds. Forcing a diver off course can remove the only stable reference along an entire rift path.",
    zhTraits: ["完整连贯的细长六肢身体", "叉状前额感知冠", "成对半透明压力翼", "黑曜蓝皮肤与浅色因果条纹", "相位转换时出现青色轮廓"],
    enTraits: ["Coherent elongated six-limbed anatomy", "Forked frontal sensory crown", "Paired translucent pressure vanes", "Obsidian-blue skin with pale causal stripes", "Cyan edges during phase transition"],
    tagsZh: ["裂隙", "相位潜跃", "六肢", "走私航路", "受控时间适应"],
    tagsEn: ["Rift", "Phase dive", "Six-limbed", "Smuggler route", "Controlled temporal adaptation"],
    illustration: "./assets/creature-concepts/riftsurf-diver/illustration.png",
    concept: "./assets/creature-concepts/riftsurf-diver/concept-sheet.png"
  },
  {
    id: "duskbell-matriarch",
    group: "wildlife",
    status: "confirmed",
    accent: "#e4a95e",
    zhName: "暮钟牧母",
    enName: "Duskbell Matriarch",
    zhSubtitle: "在灾变前鸣钟并护住整个迁徙牧群的巨型母兽",
    enSubtitle: "A giant matriarch that warns and shelters a migrating herd",
    zhSummary: "迁徙巨兽群中极少出现的高龄母体。它的空腔冠与胸部共鸣器能在时间灾害发生前读出地层和大气中的异常，并以钟鸣让幼兽静止、牧群结阵。",
    enSummary: "A rare elder female within migratory megafauna herds. Hollow crown chambers and thoracic resonators detect pre-rift anomalies in ground and atmosphere, then sound a bell-call that stills calves and draws the herd into formation.",
    zhClass: "自然生命 · 传奇巨型牧兽",
    enClass: "Natural life · Legendary herd megafauna",
    zhHabitat: "殖民地旷野、迁徙走廊、裂隙高发平原",
    enHabitat: "Colonial plains, migration corridors, rift-prone steppe",
    zhDiet: "耐辐射草本、矿盐与共生地衣",
    enDiet: "Radiation-tolerant grasses, mineral salts, symbiotic lichen",
    zhActivity: "黄昏迁徙 · 灾变预警",
    enActivity: "Dusk migration · Disaster warning",
    zhEcology: "牧母并非独立物种的女王，而是极少数活到足够年龄、共鸣冠完全发育的雌性。钟鸣发生时，幼兽会钻入其腹侧和披甲下方，成年群体则环绕形成朝外的防护阵列。",
    enEcology: "A matriarch is not a separate queen caste, but a rare female old enough for her resonant crown to fully develop. At the bell-call calves shelter beneath her mantle while adults form an outward-facing ring.",
    zhRelations: "边境殖民地会保留牧群的传统迁徙路线，并把第一声暮钟视为比官方传感器更可信的撤离信号。猎杀牧母常导致区域内整支兽群失去灾害记忆。",
    enRelations: "Frontier colonies preserve traditional migration lanes and trust the first dusk bell more than official sensors. Killing a matriarch can erase generations of disaster memory from a regional herd.",
    zhTraits: ["极为宽厚的四足巨兽体型", "带多层共鸣腔的镂空冠", "深石板色层叠保护披甲", "灰白厚皮与琥珀色共鸣器", "能容纳幼兽的腹侧庇护空间"],
    enTraits: ["Enormous broad four-legged body", "Hollow crown with layered resonant chambers", "Deep-slate protective mantle", "Ash-ivory hide with amber resonators", "Ventral shelter space for calves"],
    tagsZh: ["巨型牧兽", "灾变预警", "护幼", "迁徙记忆", "传奇"],
    tagsEn: ["Megafauna", "Disaster warning", "Calf shelter", "Migration memory", "Legendary"],
    illustration: "./assets/creature-concepts/duskbell-matriarch/illustration.png",
    concept: "./assets/creature-concepts/duskbell-matriarch/concept-sheet.png"
  },
  {
    id: "celestial-angel",
    group: "synthetic",
    status: "standardized",
    accent: "#78cfff",
    zhName: "天使机体",
    enName: "Angel Chassis",
    zhSubtitle: "承载飞升意识、以光环与光翼稳定人格的神性机体",
    enSubtitle: "A divine vessel stabilizing ascended consciousness through halos and light-wings",
    zhSummary: "械心天庭的天使是人类意识完成飞升后主动选择的神性载体，而不是以杀戮为第一印象的战斗机器人。其标准家族以平静的仿生面容、机械陶瓷上身、紧凑星能核心、无腿悬浮载体与意识光环为共同骨架；盾翼、星帆、远程圣器、环塔和星座御座都是同一机体语言下的职能配置。",
    enSummary: "Machine Celestial Court Angels are divine vessels voluntarily adopted by ascended human minds, not combat robots defined by killing. Their standardized family combines a serene biomimetic face, mechanical-ceramic upper body, compact star-energy core, legless hover vessel, and consciousness halo. Aegis wings, solar sails, remote reliquaries, orbital cathedrals, and constellation thrones are role configurations within the same visual language.",
    zhClass: "人工生命 · 标准化高阶机体",
    enClass: "Synthetic life · Standardized high-order chassis",
    zhHabitat: "天庭服务器城、轨道圣堂、舰队数据航道",
    enHabitat: "Celestial server-cities, orbital sanctums, fleet data lanes",
    zhDiet: "星能、电力与高带宽人格同步",
    enDiet: "Star-energy, electricity, and high-bandwidth mind synchronization",
    zhActivity: "常态悬浮 · 人格同步 · 任务换装",
    enActivity: "Permanent hover · Mind synchronization · Modular refit",
    zhEcology: "天使以约七成温润仿生陶瓷和三成克制的可见机械构成人形或近人形上身，保留可被原人格认同的年龄、性别、发式与神情；腰部以下由圆盘、星仪、彗核、共鸣钟或环形御座等反重力容器承载。紧凑的宝石化意识核心使用青蓝至蓝紫星辉。光环、盾翼、星帆、光翼、远程圣器或环塔既是神性象征，也是散热、姿态控制、通信和人格相干结构。",
    enEcology: "Angels form a human or near-human upper body from roughly seventy percent warm biomimetic ceramic and thirty percent restrained visible machinery, preserving the age, gender, hair, and expression recognized by the original mind. Below the waist, antigravity discs, astrolabes, comet cores, resonance bells, or ring-thrones carry the body. A compact jewel-like mind core shines in cyan through violet. Halos, aegis wings, solar sails, light-wings, remote reliquaries, and orbital cathedrals are both numinous symbols and functional systems for cooling, attitude control, communication, and mind coherence.",
    zhRelations: "天使外壳可以在任务后回收、修复并交由另一人格使用，因此机体型号不等同于个人身份。飞升者可以保留年龄、性别与容貌特征，但机体必须呈现他们主动选择的新存在方式，而不是把人格囚禁在无表情兵器中。上位天使只是载荷等级，不是灵魂或人格的高低。",
    enRelations: "Angel shells can be recovered, repaired, and assigned to another mind after a mission, so chassis model is not personal identity. Ascendants may retain age, gender, and facial identity, but the body must read as a chosen mode of existence—not a person imprisoned inside an expressionless weapon. An Upper Angel denotes payload grade, never the worth of a soul or person.",
    zhTraits: ["平静、可亲且能保留原人格特征的仿生面容", "约七成机械陶瓷与三成精密科技结构的材质平衡", "宝石化紧凑星能核心，不使用敞开式机械胸腔", "以反重力意识容器取代双腿和脚部", "光环及可配置翼系同时承担神性表达与人格稳定功能"],
    enTraits: ["Serene approachable biomimetic face preserving personal identity", "A balance of roughly seventy percent mechanical ceramic and thirty percent precise technology", "Compact jewel-like star core with no open mechanical chest cavity", "Antigravity mind vessel instead of legs or feet", "Halo and configurable wing systems serve both numinous expression and mind coherence"],
    zhKnownFormsNote: "以下形象均已纳入天使家族标准。它们共享仿生面容、机械陶瓷上身、紧凑核心、无腿悬浮载体与意识光环，是职能换装而非独立物种、成长阶段或人格等级。",
    enKnownFormsNote: "The following expressions are approved within the Angel family standard. They share a biomimetic face, mechanical-ceramic torso, compact core, legless hover vessel, and consciousness halo; they are role refits rather than separate species, growth stages, or ranks of personhood.",
    knownForms: [
      {
        zhName: "天使—星光开悟者",
        enName: "Angel—Starlight Enlightener",
        zhType: "人格承载型 · 星能演算",
        enType: "Mind-bearing role · Star-energy computation",
        zhDescription: "强化胸部意识核心、星图光环与演算翼，使飞升人格在移动中解析星能并获得启示。仿生面容与悬浮结构必须保持候选骨架的共同神性。",
        enDescription: "Strengthens the consciousness core, star-map halo, and computation wings so the ascended mind interprets star-energy while moving. The biomimetic face and floating structure must preserve the selected frame's divine identity."
      },
      {
        zhName: "天使—阵线统御官",
        enName: "Angel—Frontline Commander",
        zhType: "指挥型 · 阵亡节点回收",
        enType: "Command role · Lost-node recovery",
        zhDescription: "扩展人格光环与翼状中继结构，用于收集阵亡节点、保存记忆并调度后备机体。指挥感应结构应像庄严冠冕，而不是战术头盔。",
        enDescription: "Expands the mind halo and winglike relay structures to gather fallen nodes, preserve memory, and route reserve bodies. Command sensors should read as a dignified crown rather than a tactical helmet."
      },
      {
        zhName: "上位天使—炮台巡游者",
        enName: "Upper Angel—Turret Roamer",
        zhType: "重载型 · 移动炮台",
        enType: "Heavy role · Mobile turret",
        zhDescription: "以强化环翼或翼幕承载可收纳的远程防卫模块；非战斗状态下武装必须完全服从飞升载体的神圣主轮廓，不能让炮台成为第一视觉印象。",
        enDescription: "Carries retractable ranged defense modules within reinforced ring-wings or a wing canopy. Outside combat, armament must remain subordinate to the sacred ascension-vessel silhouette and never become the first visual impression."
      }
    ],
    tagsZh: ["械心天庭", "人工生命", "标准机体", "上传人格", "机械陶瓷", "悬浮载体", "意识光环"],
    tagsEn: ["Machine Celestial Court", "Synthetic life", "Standard chassis", "Uploaded mind", "Mechanical ceramic", "Hover vessel", "Mind halo"],
    illustration: "./assets/creature-concepts/celestial-angel/explorations-round-2/03-solar-sail-oracle.png",
    concept: "./assets/creature-concepts/celestial-angel/explorations-round-2/01-aegis-prayer-guardian.png",
    zhConceptNote: "八套获准形象共同定义天使机体，而非要求所有个体采用同一种翅膀或底座。卡牌职能可以从盾翼、星帆、远程圣器、环塔、彗核与星座御座中派生，但必须保持共同家族骨架。",
    enConceptNote: "Eight approved expressions jointly define the Angel chassis; individual bodies need not share one wing or base. Card roles may derive from aegis wings, solar sails, remote reliquaries, orbital cathedrals, comet cores, and constellation thrones while preserving the shared family invariants.",
    specimens: [
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/01-aegis-prayer-guardian.png", zh: "标准形象 A1 · 盾翼祷卫", en: "Approved A1 · Aegis Prayer Guardian" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/02-star-reliquary-choir.png", zh: "标准形象 A2 · 星铳圣咏", en: "Approved A2 · Star-Reliquary Choir" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/03-solar-sail-oracle.png", zh: "标准形象 A3 · 日帆神谕", en: "Approved A3 · Solar-Sail Oracle" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/04-orbital-cathedral-ascendant.png", zh: "标准形象 A4 · 环塔飞升者", en: "Approved A4 · Orbital-Cathedral Ascendant" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/05-aegis-ring-archon.png", zh: "标准形象 A5 · 盾环执政者", en: "Approved A5 · Aegis-Ring Archon" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/06-orbital-star-ordinance.png", zh: "标准形象 A6 · 星轨圣械", en: "Approved A6 · Orbital Star Ordinance" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/07-comet-core-pilgrim.png", zh: "标准形象 A7 · 彗核巡礼者", en: "Approved A7 · Comet-Core Pilgrim" },
      { src: "./assets/creature-concepts/celestial-angel/explorations-round-2/08-constellation-throne.png", zh: "标准形象 A8 · 星座御座", en: "Approved A8 · Constellation Throne" }
    ]
  },
  {
    id: "celestial-sprite",
    group: "synthetic",
    status: "standardized",
    accent: "#61e6ff",
    zhName: "天庭机灵",
    enName: "Celestial Sprite",
    zhSubtitle: "把路线经验写入悬浮系统的可爱小型伴随机",
    enSubtitle: "An adorable small companion that writes route experience into its hover system",
    zhSummary: "机灵是械心天庭最常见的小型悬浮伴随机谱系。它们以低成本标准机体执行跑腿、侦察、维护和节点接力，并会把累计移动经验实时固化为更高效的飘行、巡航与高速穿梭模式。",
    enSummary: "Celestial Sprites are the Machine Celestial Court's most common small hovering companion lineage. Their low-cost standard bodies run errands, scout, maintain systems, and relay nodes, continuously compiling traveled routes into more efficient drift, cruise, and high-speed traversal modes.",
    zhClass: "人工生命 · 学习型伴随机",
    enClass: "Synthetic life · Learning companion machine",
    zhHabitat: "服务器花园、维护夹层、舰内通道与数据驿站",
    enHabitat: "Server gardens, maintenance interspaces, ship corridors, data relays",
    zhDiet: "微型星能电池、感应充电与路线数据",
    enDiet: "Micro star-cells, inductive charging, and route data",
    zhActivity: "常态悬浮 · 路线学习 · 群体接力",
    enActivity: "Permanent hover · Route learning · Group relay",
    zhEcology: "标准机灵主体直径约45厘米，拥有圆润的珍珠白泪滴形机身、单片青色表情目镜、两枚后掠感知耳鳍、腹部椭圆学习核心、两只小型三指工具手与底部反重力孔。它们从不长出腿、脚或轮子，也不会接触地面；可爱感来自圆润比例、好奇的倾斜姿态和会变化的目镜表情。",
    enEcology: "A standard Sprite has a body about 45 centimeters across, with a rounded pearl-white teardrop shell, one cyan expressive visor, two swept-back sensor ear-fins, an oval belly learning-core, two tiny three-finger tool hands, and a ventral antigravity aperture. It never has legs, feet, or wheels and never touches the ground; its charm comes from round proportions, curious tilts, and responsive visor expressions.",
    zhRelations: "机灵每完成一段累计路程，就会逐级展开机身下方的同心悬浮环与两枚矢量鳍：由安静飘行切换至灵活巡航，最终进入高速路线穿梭。这是同一悬浮机体的软件与硬件展开，不是成长、进化或更换物种。不同职能只能在背部硬点、工具手和小型货舱上换装。",
    enRelations: "After accumulating route distance, a Sprite progressively deploys concentric hover rings and two vector fins beneath its body, moving from quiet drift to agile cruise and finally high-speed route traversal. This is deployment of software and hardware in the same hovering body—not growth, evolution, or species replacement. Role changes are confined to the back hardpoint, tool hands, and small cargo pods.",
    zhTraits: ["圆润泪滴形悬浮机身与单片青色表情目镜", "两枚后掠的长形感知耳鳍", "腹部中央可见的椭圆学习核心", "两只小型三指工具手且绝不具有腿、脚或轮子", "同心悬浮环与矢量鳍依次展开但身体比例不变"],
    enTraits: ["Rounded teardrop hover body with one expressive cyan visor", "Two long swept-back sensor ear-fins", "Visible oval learning-core centered on the belly", "Two tiny three-finger tool hands and absolutely no legs, feet, or wheels", "Concentric hover rings and vector fins deploy without changing body proportions"],
    tagsZh: ["械心天庭", "人工生命", "悬浮伴随机", "路线学习", "可爱", "高速穿梭"],
    tagsEn: ["Machine Celestial Court", "Synthetic life", "Hover companion", "Route learning", "Adorable", "Fast traversal"],
    illustration: "./assets/creature-concepts/celestial-sprite/illustration-v2.png",
    concept: "./assets/creature-concepts/celestial-sprite/concept-sheet-v2.png"
  },
  {
    id: "crystal-spirit",
    group: "sapient",
    status: "umbrella",
    accent: "#9ef4ff",
    zhName: "晶灵",
    enName: "Crystal Spirit",
    zhSubtitle: "以晶格稳定光子与电磁共振的智慧生命总类",
    enSubtitle: "A sapient umbrella stabilized by crystalline resonance",
    zhSummary: "晶灵的真正意识是晶格中自组织的光子与电磁共振，而非某一块会说话的矿石。普通星能矿只可能成为容器，绝不自动等同于有意识的晶灵。",
    enSummary: "A Crystal Spirit's mind is self-organizing photon and electromagnetic resonance stabilized in a lattice, not a talking rock. Ordinary star ore may become a vessel but is never automatically conscious.",
    zhClass: "智慧生命总类 · 共振生命",
    enClass: "Sapient umbrella · Resonant life",
    zhHabitat: "晶体母星、星能矿脉、人工共振庭院",
    enHabitat: "Living crystal worlds, star-ore veins, resonance gardens",
    zhDiet: "吸收光、电磁能与结构化共振",
    enDiet: "Light, electromagnetic energy, structured resonance",
    zhActivity: "长期观察 · 低速迁移 · 智慧交流",
    enActivity: "Long observation · Slow migration · Sapient exchange",
    zhEcology: "每个晶灵都有承载意识的核心，以及沿倾斜轨道运动的独立晶体。高阶晶灵会通过“晶火点燃”赋予合适晶格以智慧。普通个体多为和平观察者；神谕晶灵读取的是多个可能未来，而非唯一命运。",
    enEcology: "Every spirit has a consciousness-bearing core and separate crystals moving on inclined atom-like orbits. Higher spirits kindle suitable lattices into awareness. Most are peaceful observers; Oracle Spirits read possible futures rather than a single fate.",
    zhRelations: "人类常把晶灵误判为资源、神谕装置或装饰性矿物。自由航商会已开始承认能自主签约的晶灵个体，但关于无形共振生命的法律人格仍存在巨大争议。",
    enRelations: "Humans often misclassify Crystal Spirits as resources, oracle devices, or decorative minerals. The Guild recognizes self-contracting individuals, but legal personhood for diffuse resonance minds remains disputed.",
    zhTraits: ["意识核心与独立轨道晶体", "仅由光和共振连接的分离结构", "不要求面孔、肢体、固定矿物或固定颜色", "通过轨道姿态、折射和响应光表达意识"],
    enTraits: ["Consciousness-bearing core and independent orbital crystals", "Separated structures joined only by light and resonance", "No required face, limbs, mineral, or color", "Awareness expressed through orbit, refraction, and responsive light"],
    zhConceptNote: "晶灵并非单一物种外形。需要先确定普通观察者、神谕晶灵、点燃者等子类，再分别建立概念图，避免把某一种晶格结构误设为全族标准。",
    enConceptNote: "Crystal Spirits have no single species silhouette. Observer, Oracle, and Kindler subtypes should be defined before separate concept sheets are created, so one lattice pattern does not become a false universal standard.",
    tagsZh: ["智慧生命", "光子意识", "晶火点燃", "轨道晶体", "总类待拆分"],
    tagsEn: ["Sapient", "Photonic mind", "Crystal kindling", "Orbital crystals", "Umbrella pending"],
    illustration: "./assets/card-art/orbital-crystal-spirit/orbital-crystal-spirit-01.png",
    concept: null,
    specimens: [
      { src: "./assets/card-art/oracle-crystal-spirit/oracle-crystal-spirit-01.png", zh: "神谕晶灵 · 已知高阶个体", en: "Oracle Spirit · Known high-order individual" }
    ]
  },
  {
    id: "avatar",
    group: "sapient",
    status: "umbrella",
    accent: "#a8f0a0",
    zhName: "兽裔",
    enName: "Avatar",
    zhSubtitle: "由神树分配适应性显化基因的人类后裔总类",
    enSubtitle: "Human descendants assigned adaptive manifestations by the God Tree",
    zhSummary: "兽裔首先是拥有社会、文化与人格的人，而不是可按动物外形成批分类的奇兽。神树为每个个体分配独立而永久的适应性基因，显化可呈动物、龙族或精灵型。",
    enSummary: "Avatars are people with culture, society, and individual identity—not wildlife sorted by animal appearance. The God Tree assigns each person a permanent adaptive manifestation that may be animal, draconic, or elf-like.",
    zhClass: "智慧人类分支 · 显化生命",
    enClass: "Sapient human lineage · Manifested life",
    zhHabitat: "造物之森及跨星域兽裔聚落",
    enHabitat: "The Creation Grove and Avatar settlements across space",
    zhDiet: "依个体显化与人类基础生理而变化",
    enDiet: "Varies by manifestation and human baseline physiology",
    zhActivity: "完整社会活动 · 个体差异极大",
    enActivity: "Full social life · Extreme individual variation",
    zhEcology: "显化基因来自同一棵神圣神树，却不会简单继承父母外形。功能性适应可能包括夜视、保温皮毛、平衡尾、感压角、攀爬足或抗辐射鳞片。一旦表达，显化通常会伴随个体终生。",
    enEcology: "Manifestation genes originate from one sacred God Tree but do not simply copy parental appearance. Adaptations may include low-light vision, thermal fur, balancing tails, pressure horns, climbing feet, or radiation-resistant scales, and usually remain for life.",
    zhRelations: "外部社会常将兽裔浪漫化、商品化或误判为动物。图鉴只记录其生物学原则，不以“习性”替代文化，不把任何单一个体当作整个族群的标准代表。",
    enRelations: "Outside societies often romanticize, commodify, or animalize Avatars. This archive records biological principles without replacing culture with 'instinct' or treating any one person as a universal representative.",
    zhTraits: ["保留清晰的智慧人格与社会行为", "显化可为完整兽型拟人、龙族型或克制的精灵型", "全身解剖应与功能性适应保持一致", "服装与装备会为尾、角、耳、爪及足型重新设计"],
    enTraits: ["Clearly sapient personality and social behavior", "Manifestations may be full furry, draconic, or restrained elf-like forms", "Whole-body anatomy follows functional adaptation", "Clothing and equipment adapt to tails, horns, ears, claws, and feet"],
    zhConceptNote: "兽裔是拥有大量独立显化谱系的文明人群。需要先选定具体子类与角色——例如鹿型疗愈师、龙型重装者或精灵型侦察者——再生成插画与概念图。",
    enConceptNote: "Avatars are a civilization containing many distinct manifestation lineages. A concrete subtype and person—such as a deer healer, draconic heavy, or elf-like scout—must be chosen before illustration and concept work.",
    tagsZh: ["智慧人类", "神树", "适应性显化", "个体化", "总类待拆分"],
    tagsEn: ["Sapient human", "God Tree", "Adaptive manifestation", "Individualized", "Umbrella pending"],
    illustration: "./assets/card-art/creation-grove-healer/creation-grove-healer-01.png",
    concept: null
  },
  {
    id: "nebula-manifestation",
    group: "cosmic",
    status: "boundary",
    accent: "#b684ff",
    zhName: "星云体",
    enName: "Nebula Manifestation",
    zhSubtitle: "宇宙法则在局部现实中的执行投影",
    enSubtitle: "A local projection through which cosmic law acts",
    zhSummary: "星云体不是政治帝国，也不是普通太空动物，而是宇宙观察和执行自身法则的局部显化。战场上出现的形体只是真正宇宙尺度存在的有限投影。",
    enSummary: "Nebula Manifestations are neither a political empire nor ordinary space animals. They are local forms through which the universe observes and enforces its own laws; battlefield bodies are limited projections of cosmic-scale beings.",
    zhClass: "边界存在 · 宇宙法则投影",
    enClass: "Boundary entity · Projection of cosmic law",
    zhHabitat: "引力异常、恒星诞生区、时间裂隙修正带",
    enHabitat: "Gravity anomalies, stellar nurseries, temporal correction zones",
    zhDiet: "不适用；通过局部法则维持投影",
    enDiet: "Not applicable; projection sustained by local law",
    zhActivity: "执行原则 · 超越常规道德判断",
    enActivity: "Executes principles beyond ordinary morality",
    zhEcology: "每个显化体执行一个原则，例如引力、恒星诞生、距离、守恒、坍缩或时间异常修正。其外缘由星云、尘埃和星光组成并持续消散，紧凑的明亮意志核心维持局部形体。",
    enEcology: "Each manifestation executes a principle such as gravity, stellar birth, distance, conservation, collapse, or temporal correction. Nebulae, dust, and stars dissolve at its edges while a compact brilliant will-core sustains the local body.",
    zhRelations: "凡人只能根据事件结果推测星云体的原则，无法假定它们友善或敌对。星航恶兆—巨鳐是已知显化个体之一，其形体和行为不能被视为整个总类的统一标准。",
    enRelations: "Mortals infer a manifestation's principle from outcomes and cannot assume friendship or hostility. The Starfaring Omen—Great Ray is one known individual, not a universal body plan for the entire class.",
    zhTraits: ["紧凑明亮的意志核心", "由星云、尘埃与星体组成的半透明形体", "引力弧与空间透镜效应", "以舰船、空间站或世界作为尺度参照", "轮廓可从巨鳐、环体到抽象星群完全不同"],
    enTraits: ["Compact brilliant will-core", "Translucent body of nebulae, dust, and stars", "Gravitational arcs and spatial lensing", "Ships, stations, or worlds as scale cues", "Silhouettes range from rays and ring-beings to abstract clusters"],
    knownForms: [
      {
        zhName: "星航恶兆—巨鳐",
        enName: "Starfaring Omen—Great Ray",
        zhType: "已确认显化 · 深空巨构级",
        enType: "Confirmed manifestation · Deep-space megastructure",
        zhDescription: "已知投影呈无面巨鳐轮廓：宽阔的中央体、两翼般展开的星云结构与紧凑的青白意志核心。它执行“阵列密度矫正”法则：当舰船、巨构或其他大型质量在局部空间过度聚集时，巨鳐会折叠距离并释放引力秩序波，强制重新分配阵列间距。",
        enDescription: "Its known projection resembles a faceless great ray: a broad central body, two winglike nebular structures, and a compact cyan-white will-core. It executes the law of formation-density correction: when ships, megastructures, or other great masses become excessively concentrated in local space, the Great Ray folds distance and releases gravitational order waves that forcibly redistribute their spacing."
      }
    ],
    protocolZh: [
      "先记录被改变的物理结果，再推断其执行原则；绝不能只凭外形命名或分类。",
      "不要默认星云体友善或敌对。应优先疏散高密度舰群、停止扩大异常，并保留远距观测窗口。",
      "持续测量意志核心、空间透镜、引力弧和受影响常数；在无法理解其局部法则与后果时，不应贸然接近或攻击。"
    ],
    protocolEn: [
      "Record the altered physical outcomes before inferring the executed principle; never classify a manifestation by silhouette alone.",
      "Do not assume friendship or hostility. Disperse dense fleet formations, stop escalating the anomaly, and preserve a long-range observation window.",
      "Track the will-core, spatial lensing, gravity arcs, and affected constants. Do not approach or attack until the local law and likely consequences are understood."
    ],
    zhConceptNote: "星云体同样是原则驱动的总类。本页保留已确认个体插画；后续概念图应按具体法则执行者分别制作，而不是建立统一物种解剖。",
    enConceptNote: "Manifestations are also principle-driven umbrellas. This page retains a confirmed individual illustration; future sheets should be made per executed law rather than as universal species anatomy.",
    tagsZh: ["宇宙法则", "投影", "意志核心", "巨型存在", "非生物"],
    tagsEn: ["Cosmic law", "Projection", "Will-core", "Vast entity", "Non-biological"],
    illustration: "./assets/card-art/starfaring-omen-great-ray/starfaring-omen-great-ray-02.png",
    concept: null,
    specimens: [
      { src: "./assets/card-art/starfaring-omen-great-ray/starfaring-omen-great-ray-01.png", zh: "星航恶兆—巨鳐 · 观测记录 A", en: "Starfaring Omen—Great Ray · Record A" }
    ]
  },
  {
    id: "hollow-null",
    group: "anomaly",
    status: "boundary",
    accent: "#8f75ff",
    zhName: "空亡体",
    enName: "Hollow-Null",
    zhSubtitle: "矛盾时间线被压缩后产生的因果残骸",
    enSubtitle: "Causal debris formed from compressed contradictory timelines",
    zhSummary: "空亡体并不构成自然物种。它们是互相矛盾的时间状态在裂隙中被压缩后形成的因果残骸，以破坏结构、顺序与记忆中的秩序来增加熵。",
    enSummary: "Hollow-Nulls are not a natural species. They are causal debris created when contradictory timeline states are compressed inside a rift, increasing entropy by destroying order in structures, sequences, and memory.",
    zhClass: "边界存在 · 因果异常",
    enClass: "Boundary entity · Causal anomaly",
    zhHabitat: "时间裂隙、黑午遗迹、空亡时主灾区",
    enHabitat: "Time rifts, Black Noon ruins, Time-Lord disasters",
    zhDiet: "不摄食物质；消耗因果与结构秩序",
    enDiet: "Consumes causal and structural order, not matter",
    zhActivity: "不连续移动 · 失序扩散",
    enActivity: "Discontinuous movement · Entropic spread",
    zhEcology: "所有空亡体都围绕不反射任何光线的因果空洞组织形体。肢体可能同时占据矛盾位置，组织同时生长与侵蚀，附近直线、光照和行动顺序都会断裂。力量越高，代表失稳程度越强，而非肉体更结实。",
    enEcology: "Every Hollow-Null organizes around a causal void that reflects no light. Limbs occupy contradictory positions, tissue grows and erodes at once, and nearby lines, lighting, and action order break. Greater power means greater instability, not tougher flesh.",
    zhRelations: "击杀普通空亡体只能清除局部残骸。迷离型、飞翔型与咆哮型是灾难的不同表现，不构成进化关系；每场大型“时亡灾变”都有一名空亡时主作为唯一核心与稳定吸引子。摧毁时主会让因果空洞坍缩、其他表现形态消散并恢复局部时间。",
    enRelations: "Destroying an ordinary Hollow-Null clears only local debris. Lost, flying, and roaring forms are parallel expressions of a disaster rather than evolutionary stages; every major Time-Death catastrophe has one Hollow Time Lord as its singular core and stabilizing attractor. Destroying it collapses the causal void, disperses the other expressions, and allows local time to resume.",
    zhTraits: ["完全不反光的中央因果空洞", "互不对齐的解剖或材质碎片", "同一肢体的矛盾时间位置", "同时生长和侵蚀的表面", "断帧式移动与破碎环境线条"],
    enTraits: ["Perfectly lightless central causal void", "Misaligned anatomical and material fragments", "Contradictory temporal positions of the same limb", "Simultaneous growth and erosion", "Frame-skipping movement and broken environmental lines"],
    knownForms: [
      {
        zhName: "迷离的空亡体",
        enName: "Lost Hollow-Null",
        zhType: "灾难表现 · 迷离型",
        enType: "Disaster expression · Lost form",
        zhDescription: "由少量互不相容的生物、陶瓷与机械残片围绕小型因果空洞拼接而成。它们像迷路般爬行或追逐残存秩序，是最常见的局部因果残骸；形体简陋不代表它仍是可理解的自然生命。",
        enDescription: "A few incompatible biological, ceramic, and mechanical fragments assemble around a small causal void. These forms crawl as if lost and pursue pockets of remaining order. Their crude bodies make them common local debris, not understandable natural animals.",
        concept: "./assets/creature-concepts/hollow-null/lost-hollow-null-concept-sheet.png"
      },
      {
        zhName: "飞翔型空亡体",
        enName: "Flying Hollow-Null",
        zhType: "灾难表现 · 多轨迹型",
        enType: "Disaster expression · Multi-trajectory form",
        zhDescription: "没有用于飞行的普通翅膀；同一形体会同时占据数条互不相容的空中轨迹，再跳过中间过程突然抵达其中一个位置。漂浮残片围绕因果空洞不断改写前后关系。",
        enDescription: "It has no ordinary wings. The same body occupies several incompatible aerial trajectories, then skips the intervening motion and arrives at one of them. Floating fragments continually rewrite their before-and-after relationship around the causal void.",
        concept: "./assets/creature-concepts/hollow-null/flying-hollow-null-concept-sheet.png"
      },
      {
        zhName: "咆哮型空亡体",
        enName: "Roaring Hollow-Null",
        zhType: "灾难表现 · 失序波型",
        enType: "Disaster expression · Disorder-wave form",
        zhDescription: "所谓“咆哮”不是单纯声波，而是先于声音抵达的因果失序前沿。连接件会脱落、结构会锈蚀、记忆与行动顺序会被打乱，随后观察者才听见无法对应发声器官的回响。",
        enDescription: "Its 'roar' is not merely sound but a causal disorder front that arrives first. Fasteners separate, structures corrode, and memory and action order scramble before observers hear an echo with no matching vocal organ.",
        concept: "./assets/creature-concepts/hollow-null/roaring-hollow-null-concept-sheet.png"
      },
      {
        zhName: "空亡时主",
        enName: "Hollow Time Lord",
        zhType: "灾变核心 · 稳定吸引子",
        enType: "Catastrophe core · Stabilizing attractor",
        zhDescription: "每次大型时亡灾变只会围绕一名时主形成。它不是其他空亡体的进化终点或普通首领，而是维持整场灾变的因果核心与稳定吸引子：各种表现形态、时间断层和失序现象都被其空洞组织。摧毁时主可令灾变失去核心并开始平息。",
        enDescription: "Each major Time-Death catastrophe forms around one Time Lord. It is neither the evolutionary endpoint nor an ordinary leader of other Hollow-Nulls, but the causal core and stabilizing attractor of the entire event: every expression, temporal fracture, and disorder phenomenon is organized by its void. Destroying it removes the catastrophe's core and allows the event to subside.",
        concept: "./assets/creature-concepts/hollow-null/hollow-time-lord-concept-sheet.png"
      }
    ],
    protocolZh: [
      "不要以体型、外甲或物理创伤判断威胁与死亡；先确认中央因果空洞是否仍在组织周围碎片。",
      "建立不受影响的参照线与同步时标，隔离断裂区域，并按不连续移动预留多条可能路径。",
      "大型时亡灾变中应优先定位空亡时主。核心仍存在时，反复清除其他表现形态只能短暂减缓熵增。"
    ],
    protocolEn: [
      "Do not judge threat or death by size, armor, or physical injury. First confirm whether the central causal void still organizes nearby fragments.",
      "Establish unaffected reference lines and synchronized clocks, isolate broken zones, and reserve multiple possible paths for discontinuous movement.",
      "In a major Time-Death event, prioritize locating the Hollow Time Lord. While the anchor persists, clearing other expressions only slows entropy temporarily."
    ],
    zhConceptNote: "空亡体没有统一物种解剖，因此不建立覆盖全族的概念图。各灾难表现与空亡时主的独立设定板已收录在“已知形态与显化”中。",
    enConceptNote: "Hollow-Nulls have no universal species anatomy, so the archive does not impose one class-wide concept sheet. Separate setting sheets for each disaster expression and the Hollow Time Lord appear under Known Forms.",
    tagsZh: ["因果残骸", "空洞", "熵增", "时间灾变", "非生物"],
    tagsEn: ["Causal debris", "Void", "Entropy", "Temporal disaster", "Non-biological"],
    illustration: "./assets/card-art/lost-hollow-null/lost-hollow-null-01.png",
    concept: null,
    specimens: [
      { src: "./assets/card-art/hollow-time-lord/hollow-time-lord-01.png", zh: "空亡时主 · 时亡灾变核心", en: "Hollow Time Lord · Time-Death anchor" }
    ]
  }
];
