// Generated by tools/build-wiki.mjs. Edit docs/rules instead.
window.TBH_WIKI = {
  "sections": [
    {
      "id": "start",
      "title": "开始阅读",
      "pages": [
        "start/overview",
        "start/quickstart"
      ]
    },
    {
      "id": "concepts",
      "title": "核心概念",
      "pages": [
        "concepts/board",
        "concepts/glossary"
      ]
    },
    {
      "id": "match",
      "title": "对局与回合",
      "pages": [
        "match/turns"
      ]
    },
    {
      "id": "economy",
      "title": "资源与卡牌流转",
      "pages": []
    },
    {
      "id": "actions",
      "title": "基础行动与战斗",
      "pages": [
        "actions/combat"
      ]
    },
    {
      "id": "effects",
      "title": "能力与效果结算",
      "pages": [
        "effects/targets",
        "effects/resolution"
      ]
    },
    {
      "id": "reference",
      "title": "关键词与卡牌设计约定",
      "pages": []
    },
    {
      "id": "rulings",
      "title": "裁定与案例",
      "pages": [
        "rulings/pending"
      ]
    },
    {
      "id": "contributing",
      "title": "维护与开发参考",
      "pages": []
    }
  ],
  "pages": [
    {
      "title": "开始阅读",
      "id": "start",
      "status": "draft",
      "file": "start/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>Wiki 的范围、状态与阅读方式。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/start/overview\">游戏概览\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/start/quickstart\">快速入门\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/concepts\">核心概念\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "游戏概览",
      "id": "start/overview",
      "status": "draft",
      "file": "start/overview.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/start\">开始阅读\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "快速入门",
      "id": "start/quickstart",
      "status": "draft",
      "file": "start/quickstart.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/start\">开始阅读\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "核心概念",
      "id": "concepts",
      "status": "draft",
      "file": "concepts/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>对象、区域、空间与术语。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/concepts/board\">棋盘与空间\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/concepts/glossary\">术语索引\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/match\">对局与回合\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "棋盘与空间",
      "id": "concepts/board",
      "status": "draft",
      "file": "concepts/board.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/concepts\">核心概念\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "术语索引",
      "id": "concepts/glossary",
      "status": "draft",
      "file": "concepts/glossary.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/concepts\">核心概念\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "对局与回合",
      "id": "match",
      "status": "draft",
      "file": "match/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>对局、回合与阶段的组织。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/match/turns\">回合与阶段\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/economy\">资源与卡牌流转\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "回合与阶段",
      "id": "match/turns",
      "status": "draft",
      "file": "match/turns.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/match\">对局与回合\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "资源与卡牌流转",
      "id": "economy",
      "status": "draft",
      "file": "economy/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "章节内容",
          "text": "章节内容",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>资源与卡牌流转的整理入口。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"章节内容\">章节内容\u003c/h2>\n\u003cp>未完成。具体条目将在规则讨论中逐步建立。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/actions\">基础行动与战斗\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "基础行动与战斗",
      "id": "actions",
      "status": "draft",
      "file": "actions/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>玩家行动与战斗的整理入口。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/actions/combat\">攻击与伤害\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/effects\">能力与效果结算\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "攻击与伤害",
      "id": "actions/combat",
      "status": "draft",
      "file": "actions/combat.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/actions\">基础行动与战斗\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "能力与效果结算",
      "id": "effects",
      "status": "draft",
      "file": "effects/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>能力与精确结算语义。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/effects/targets\">目标与选择\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects/resolution\">效果结算过程\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/reference\">关键词与卡牌设计约定\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "目标与选择",
      "id": "effects/targets",
      "status": "draft",
      "file": "effects/targets.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/effects\">能力与效果结算\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/actions\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "效果结算过程",
      "id": "effects/resolution",
      "status": "draft",
      "file": "effects/resolution.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/effects\">能力与效果结算\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/actions\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "关键词与卡牌设计约定",
      "id": "reference",
      "status": "draft",
      "file": "reference/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "章节内容",
          "text": "章节内容",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>关键词、状态与卡面约定。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"章节内容\">章节内容\u003c/h2>\n\u003cp>未完成。具体条目将在规则讨论中逐步建立。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/rulings\">裁定与案例\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "裁定与案例",
      "id": "rulings",
      "status": "draft",
      "file": "rulings/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "本章目录",
          "text": "本章目录",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>已确认裁定与未决问题。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"本章目录\">本章目录\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/rulings/pending\">待裁定问题\u003c/a>\u003c/li>\n\u003c/ul>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/contributing\">维护与开发参考\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "待裁定问题",
      "id": "rulings/pending",
      "status": "draft",
      "file": "rulings/pending.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "规则与示例",
          "text": "规则与示例",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>本页尚未完成，等待逐项讨论与整理。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 暂无已确认的规则正文。本页标题仅用于组织文档，不代表玩法已确定。\u003c/p>\n\u003ch2 id=\"规则与示例\">规则与示例\u003c/h2>\n\u003cp>未完成。待确认本主题的定义、边界与案例后填写。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/rulings\">裁定与案例\u003c/a>\u003c/li>\n\u003cli>\u003ca href=\"#/effects\">相关主题\u003c/a>\u003c/li>\n\u003c/ul>\n"
    },
    {
      "title": "维护与开发参考",
      "id": "contributing",
      "status": "draft",
      "file": "contributing/index.md",
      "toc": [
        {
          "id": "内容状态",
          "text": "内容状态",
          "depth": 2
        },
        {
          "id": "章节内容",
          "text": "章节内容",
          "depth": 2
        },
        {
          "id": "相关页面",
          "text": "相关页面",
          "depth": 2
        }
      ],
      "html": "\u003cp>规则维护与开发参考入口。\u003c/p>\n\u003ch2 id=\"内容状态\">内容状态\u003c/h2>\n\u003cp>\u003cstrong>待整理。\u003c/strong> 本章仅建立文档位置，尚无已确认规则。旧文档不会自动成为这里的正式内容。\u003c/p>\n\u003ch2 id=\"章节内容\">章节内容\u003c/h2>\n\u003cp>未完成。具体条目将在规则讨论中逐步建立。\u003c/p>\n\u003ch2 id=\"相关页面\">相关页面\u003c/h2>\n\u003cul>\n\u003cli>\u003ca href=\"#/start\">开始阅读\u003c/a>\u003c/li>\n\u003c/ul>\n"
    }
  ]
};
